name: Build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore DbLoader.csproj

      - name: Build Project
        run: |
          msbuild.exe DbLoader.csproj /p:platform="Any CPU" /p:configuration="Release"

      - name: Upload build files
        uses: actions/upload-artifact@v3
          with:
            name: release
            path: D:\a\dbloader-git\dbloader-git\bin\Release\net472\dbloader.exe

